config/routes.rb
UserBase::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :properties
  
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/manage_properties', to: 'properties#manage_properties', via: 'get'

end

app/models/property.rb
class Property < ActiveRecord::Base
	before_save :ensure_owner

	belongs_to :user

	validates :user_id, presence: true
	validates :name, presence: true, length: {minimum: 3, maximum: 120}
	validates :description, presence: true
	validates :beds, presence: true
	validates :baths, presence: true
	validates :rent, presence: true



	private
		def ensure_owner
			self.user.owner?
		end

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	has_many :properties, dependent: :destroy

	validates :name, presence: true, length: {maximum: 50}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
		uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, length: {minimum: 6}

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :sign_in_user, only: [:create, :edit, :update, :destroy]
  	before_action :correct_user, only: [:edit, :update, :destroy]
  	before_action :check_if_owner, only: [:new]


	def new
		@property = Property.new
	end

	def create
		@property = current_user.properties.build(property_params)
		if @property.save
			flash[:success] = "Property Created!"
			redirect_to property_path(@property)
		else
			render 'new'
		end
	end

	def show
		@property = Property.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:notice] = "Property not found..."
		redirect_to properties_path
	end

	def index
		@properties = Property.paginate(page: params[:page])
	end

	def manage_properties
		if owner_user?
			#@properties = Property.paginate(page: params[:page])
			@properties = current_user.properties.paginate(page: params[:page])
		else
			redirect_to root_url
		end
	end

	def edit
		@property = Property.find(params[:id])
	end

	def update
		@property = Property.find(params[:id])
		if @property.update_attributes(property_params)
			flash[:success] = "Property updated"
			redirect_to @property
		else
			render 'edit'
		end
	end

	def destroy
		@property.destroy
		redirect_to properties_path
	end

	private

		def property_params
			params.require(:property).permit(:name, :description, :beds, :baths, :rent)
		end 

		#before filters

		def correct_user
			if owner_user?
				@property = current_user.properties.find_by(id: params[:id])
				if @property.nil?
					redirect_to root_url
				end
			else
				redirect_to root_url
			end
		end

		def check_if_owner
			if !owner_user?
				redirect_to root_url
			end
		end

		def sign_in_user
			unless signed_in?
				store_location
				redirect_to signin_url, notice: "Please sign in."
			end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			#sign in and redirect
			sign_in user
			redirect_back_or user
		else
			#error out, re-render form
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
  	@user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome "+@user.name+"!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    #before filters

    def sign_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns a properly formatted dynamic title for each page
	def full_title(page_title)
		base_title = "Real Estate App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def owner_user?
		if signed_in?
			current_user.owner
		end
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Sample Real Estate Listing | Rails | Eric Typaldos
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Digs", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "All Properties", properties_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Manage Properties", manage_properties_path if current_user.owner %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/properties/_property.html.erb
<li class="list-group-item"><%= link_to property.name, property %></li>

app/views/properties/edit.html.erb
<% provide(:title, 'Edit Property | '+@property.name) %>
<h1>Edit property</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Delete this Property?", @property, method: :delete,
                    data: {confirm: "You sure?"},
                    title: @property.name %>
    <%= form_for(@property) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :beds %>
      <% beds_list = (0..10) %>
      <%= f.select(:beds, options_for_select(beds_list,  @property.beds.to_s)) %>

      <%
      baths_list = []
      (0..8).each do |i|
        baths_list.insert(i, i)
        baths_list.insert(i, i+0.5)
      end
      %>

      <%= f.label :baths %>
      <%= f.select(:baths, options_for_select(baths_list.sort, @property.baths.to_i.to_s)) %>

      <%= f.label :rent %>
      <%= f.number_field :rent %>


      <%= f.submit "Save", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/properties/index.html.erb
<% provide(:title, "All Properties") %>
<div class="row">
	<h1>All properties</h1>
	<div class="col-md-6 col-md-offset-3">
	<% if @properties.any? %>
		<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
		<ul class="list-group">
			<% if owner_user? %>
			<li class="list-group-item">
				<a href="<%= new_property_path(@property) %>">
					<span class="glyphicon glyphicon-plus"></span>
					Add New Property
					</a>
			</li>
			<% end %>
			<%= render @properties %>
		</ul>
		<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
	<% else %>
		<h3>No properties currently</h3>
	<% end %>
	</div>
</div>

app/views/properties/manage_properties.html.erb
<% provide(:title, "Manage Properties") %>
<div class="row">
	<h1>Manage <small>your properties</small></h1>

	<div class="col-md-6 col-md-offset-3">
		<% if @properties.any? %>
			<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
			<ul class="list-group">
				<li class="list-group-item">
					<a href="<%= new_property_path(@property) %>">
  					<span class="glyphicon glyphicon-plus"></span>
  					Add New Property
  					</a>
  				</li>
				<%= render @properties %>
			</ul>
			<%= will_paginate @properties, renderer: BootstrapPagination::Rails %>
		<% else %>
			<h3>No properties currently</h3>
		<% end %>
	</div>
	<aside class="span3">
		<section class="text-center">
			<ul class="nav nav-pills nav-stacked">
  				<li class="active"><a href="#">Manage Properties</a></li>
  				<li><a href="#">My Profile</a></li>
  				<li><a href="#">Messages</a></li>
			</ul>
		</section>
	</aside>

</div>

app/views/properties/new.html.erb
<% provide(:title, 'Add Property') %>
<h1>Add new property</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@property) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :beds %>
      <%= f.select(:beds, options_for_select((0..10).to_a)) %>

      <%
      baths_list = []
      (0..8).each do |i|
        baths_list.insert(i, i)
        baths_list.insert(i, i+0.5)
      end
      %>

      <%= f.label :baths %>
      <%= f.select(:baths, options_for_select(baths_list.sort)) %>

      <%= f.label :rent %>
      <%= f.number_field :rent %>


      <%= f.submit "Create property", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/properties/show.html.erb
<% provide(:title, @property.name) %>
<div class="row">
	<section>
	  <h1>
	    <%= @property.name %>
	  </h1>
	  <p><%= @property.to_json %></p>
	  <%= link_to "Edit", edit_property_path(@property) %>
	  
	</section>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
<p>Contact Page</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<p>help me Help</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Digs - Sample Real Estate App</h1>
  <h2>by Eric Typaldos</h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, 'Confirm Password' %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>


<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
<ul class="users">
	<%= render @users %>
</ul>
<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>